api:
  hostname: http://api.openweathermap.org

spring:
  cache:
    type: ehcache
    ehcache:
        config: classpath:ehcache.xml
logging:
  level:
    com.shilton.weather.weatherapp.cache.ehcache: DEBUG